/* var fruites = ["apple", "banana", "Orange"];
var findFruites = fruites.indexOf("banana")
console.log(findFruites)

var ReplaceFruites = fruites.splice(findFruites, 1 ,"Mango")
console.log(ReplaceFruites)

var rmVOrag = fruites.pop("Orange")
var AddWatermelon = fruites.push("Watermelon")
console.log(fruites)
 */

// * LetterGrade
// * Given Three Number to find Largets one
// * somodibahu Traiangel ==> Need to Equal 2 value

/* var a = 9;
var b = 8;
var c = 9;

if (a == b || b == c || c == a) {
  console.log("Triangle Is Isosceles");
} else {
  console.log("Triangle Is Not Isosceles");
} */

/* var fruites = ["apple", "banana", "Orange"];
var findFruites = fruites.indexOf("banana")
console.log(findFruites)

// var ReplaceFruites = fruites.splice(findFruites, 1 ,"Mango")
// console.log(ReplaceFruites)
fruites[1] = 'Mango'
console.log(fruites)

var rmVOrag = fruites.pop("Orange")
var AddWatermelon = fruites.push("Watermelon")
console.log(fruites)
  */

// ->

var fruites = ["apple", "banana", "Orange"];
var findFruites = fruites.indexOf("banana");
console.log("Index Of Banana : " + findFruites);

fruites[1] = "Mango";
console.log(fruites);

// var ReplaceFruites = fruites.splice(findFruites, 1 ,"Mango")
// console.log(ReplaceFruites)

var rmVOrag = fruites.pop("Orange");
var AddWatermelon = fruites.push("Watermelon");
console.log(fruites);
